version: '3.8'

services:
  api:
    build: .
    container_name: contacts-service-api
    ports:
      - "8002:8002"
    volumes:
      - ./app:/app/app
      - db-data:/app/db
    environment:
      - DATABASE_URL=sqlite:///./db/contacts.db
    restart: always

volumes:
  db-data:
    name: contacts-db-data