services:
  agents:
    build:
      context: ./src/agents
      dockerfile: Dockerfile
    container_name: agents-container
    develop:
      watch:
        - path: ./src/agents
          action: sync
          target: /agents
          ignore:
            - .venv/
            - __pycache__/
        - path: ./src/agents/**/*.py
          action: sync
          target: /agents
    ports:
      - "8000:8000"
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - ./src/agents/.env
    volumes:
      - ./src/agents:/agents
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck"]
      interval: 30s
      timeout: 30s
      retries: 3

  # Add your contact service here
  contacts:
    build:
      context: ./src/contact-service
      dockerfile: Dockerfile
    container_name: contacts-service-api
    ports:
      - "8002:8002"
    volumes:
      - ./src/contact-service/app:/app/app
      - contacts-db-data:/app/db
    environment:
      - DATABASE_URL=sqlite:///./db/contacts.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 30s
      retries: 3

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: nlp_crypto_bot
    restart: unless-stopped
    env_file:
      - ./bot/.env

  telegram-mini-app:
    build:
      context: ./transaction-mini-app
      dockerfile: Dockerfile
    container_name: transaction-mini-app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: unless-stopped
    env_file:
      - ./transaction-mini-app/.env.local

# Add the volume for contacts database
volumes:
  contacts-db-data:
    name: contacts-db-data
